"""add_entity_name

Revision ID: 2ef0ea037136
Revises: 
Create Date: 2026-03-23 17:42:21.698405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef0ea037136'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('entity_name', sa.String(), nullable=True, comment='角色/實體名稱以利搜尋'))
    op.create_index(op.f('ix_entities_entity_name'), 'entities', ['entity_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_entity_name'), table_name='entities')
    op.drop_column('entities', 'entity_name')
    # ### end Alembic commands ###
