"""Add line_user_id and line_display_name to EntityModel

Revision ID: 7640d31c6554
Revises: 2ef0ea037136
Create Date: 2026-03-24 00:49:20.634060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7640d31c6554'
down_revision: Union[str, Sequence[str], None] = '2ef0ea037136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sa.Column('line_user_id', sa.String(), nullable=True, comment='綁定的 LINE 帳號 ID'))
    op.add_column('entities', sa.Column('line_display_name', sa.String(), nullable=True, comment='綁定的 LINE 顯示名稱'))
    op.create_index(op.f('ix_entities_line_user_id'), 'entities', ['line_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entities_line_user_id'), table_name='entities')
    op.drop_column('entities', 'line_display_name')
    op.drop_column('entities', 'line_user_id')
    # ### end Alembic commands ###
