"""Add line_user_id and line_display_name to Entity

Revision ID: 8a114ee1b0c9
Revises: 2ef0ea037136
Create Date: 2026-03-24 00:35:23.330683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a114ee1b0c9'
down_revision: Union[str, Sequence[str], None] = '2ef0ea037136'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
